/** Declaration file generated by dts-gen */

export function check(...args: any[]): void;

export function help(name: any, errors: any): any;

export function load(name: any): any;

export function options(name: any): any;

export function scan(): any;

export function setConfig(newConfig: any): void;

export function setFilename(newFilename: any): void;

export function validate(name: any, value: any): any;

export namespace check {
    const prototype: {
    };

}

export namespace help {
    const prototype: {
    };

}

export namespace load {
    const prototype: {
    };

}

export namespace options {
    const prototype: {
    };

}

export namespace scan {
    const prototype: {
    };

}

export namespace setConfig {
    const prototype: {
    };

}

export namespace setFilename {
    const prototype: {
    };

}

export namespace validate {
    const prototype: {
    };

}

